# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stacked}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bigg"]
  s.date = %q{2010-04-04}
  s.description = %q{Ruby wrapper for the Stack Overflow API}
  s.email = %q{ryan@getup.org.au}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "cleaner.rb",
     "lib/stacked.rb",
     "lib/stacked/answer.rb",
     "lib/stacked/badge.rb",
     "lib/stacked/base.rb",
     "lib/stacked/comment.rb",
     "lib/stacked/posttimeline.rb",
     "lib/stacked/question.rb",
     "lib/stacked/reputation.rb",
     "lib/stacked/tag.rb",
     "lib/stacked/user.rb",
     "lib/stacked/usertimeline.rb",
     "spec/sorted_by_spec.rb",
     "spec/spec_helper.rb",
     "spec/stacked/answer_spec.rb",
     "spec/stacked/badge_spec.rb",
     "spec/stacked/base_spec.rb",
     "spec/stacked/comment_spec.rb",
     "spec/stacked/question_spec.rb",
     "spec/stacked/reputation_spec.rb",
     "spec/stacked/tag_spec.rb",
     "spec/stacked/user_spec.rb",
     "spec/stacked/usertimeline_spec.rb",
     "spec/support/aliases.rb",
     "spec/support/sorted_by.rb",
     "spec/support/within.rb",
     "spec/within_spec.rb"
  ]
  s.homepage = %q{http://github.com/radar/stacked}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Stack Overflow API}
  s.test_files = [
    "spec/sorted_by_spec.rb",
     "spec/spec_helper.rb",
     "spec/stacked/answer_spec.rb",
     "spec/stacked/badge_spec.rb",
     "spec/stacked/base_spec.rb",
     "spec/stacked/comment_spec.rb",
     "spec/stacked/question_spec.rb",
     "spec/stacked/reputation_spec.rb",
     "spec/stacked/tag_spec.rb",
     "spec/stacked/user_spec.rb",
     "spec/stacked/usertimeline_spec.rb",
     "spec/support/aliases.rb",
     "spec/support/sorted_by.rb",
     "spec/support/within.rb",
     "spec/within_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.4.5"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<httparty>, ["~> 0.4.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<httparty>, ["~> 0.4.5"])
  end
end
